In [33]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
%matplotlib inline

In [34]:
placement=pd.read_csv('.spyder-py3\Placement_Data.csv')
print(placement.head())

   sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0  


In [35]:
placement=placement.drop(['sl_no','gender','ssc_p','ssc_b','hsc_p','hsc_b','hsc_s','degree_t','specialisation','salary'],axis=1)
placement.head()

degree_p workex  etest_p  mba_p      status
0     58.00     No     55.0  58.80      Placed
1     77.48    Yes     86.5  66.28      Placed
2     64.00     No     75.0  57.80      Placed
3     52.00     No     66.0  59.43  Not Placed
4     73.30     No     96.8  55.50      Placed

In [36]:
status=list(placement['status'])
status=[1 if i=='Placed' else 0 for i in status]
placement=placement.drop('status',axis=1)
placement['status']=status

workex=list(placement['workex'])
workex=[1 if i=='Yes' else 0 for i in workex]
placement=placement.drop('workex',axis=1)
placement['workex']=workex

In [38]:
placement.head()
x=placement[['degree_p','etest_p','mba_p','workex']]
y=placement[['status']]

In [41]:
from sklearn.model_selection import train_test_split 
xtrain, xtest, ytrain, ytest = train_test_split( x, y, test_size = 0.25, random_state = 1) 

In [42]:
from sklearn.preprocessing import StandardScaler 
sc_x = StandardScaler() 
xtrain = sc_x.fit_transform(xtrain)  
xtest = sc_x.transform(xtest) 
  

In [43]:
print (xtrain[0:10, :]) 

[[-0.89736633 -1.07700204  1.19315096 -0.77075249]
 [ 2.17950686  1.53760097  0.97905103 -0.77075249]
 [-0.19807697  1.58844475  0.10381054 -0.77075249]
 [ 0.08163878 -0.25656827 -0.22675975 -0.77075249]
 [ 1.62007537  0.76724063  1.56140283 -0.77075249]
 [-0.19807697 -0.77348007 -0.9427099  -0.77075249]
 [ 0.36135452 -1.41287915 -1.25101379 -0.77075249]
 [ 0.36135452 -1.27421429 -0.67037479 -0.77075249]
 [ 0.02569563  1.84574511  1.46206046  1.29743336]
 [ 0.92078601  0.61316856  0.81119669 -0.77075249]]


In [47]:
from sklearn.linear_model import LogisticRegressionCV 
classifier = LogisticRegressionCV(random_state = 1,cv=5,scoring='accuracy',n_jobs=-1,max_iter=100)
classifier.fit(xtrain,ytrain.values.ravel()) 

LogisticRegressionCV(Cs=10, class_weight=None, cv=5, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=100, multi_class='auto', n_jobs=-1, penalty='l2',
                     random_state=1, refit=True, scoring='accuracy',
                     solver='lbfgs', tol=0.0001, verbose=0)

In [48]:
classifier.score(xtest,ytest)

0.8703703703703703